#!/bin/sh

TMPFILE=/tmp/mkpb$$

trim()
{
    echo $@
}

grep callerid /etc/asterisk/pjsip.endpoint.conf > $TMPFILE

echo "<YealinkIPPhoneDirectory>"
echo ""

while read -r line
do

    x=`echo $line | cut -f2- -d'='`
    extn=`echo $x | cut -f2 -d'<' | cut -f1 -d'>'`
    name=`echo $x | cut -f1 -d'<'`

    if [ "$name" != "$extn " ]
    then
        echo "  <DirectoryEntry>"
        echo "    <Name>$name</Name>"
        echo "    <Telephone>$extn</Telephone>"
        echo "  </DirectoryEntry>"
        echo ""
    fi

done < $TMPFILE

echo "  <DirectoryEntry>"
echo "    <Name>On call engineer</Name>"
echo "    <Telephone>2649</Telephone>"
echo "  </DirectoryEntry>"
echo ""

echo "</YealinkIPPhoneDirectory>"

