#!/bin/sh

if [ $# -gt 5 ] || [ $# -lt 4 ]
then
    echo "mkphone <mac address> <phone type> <firmware> <line 1> [<line 2>]"
    exit 1
fi

mac=`echo $1 | sed -e 's/://g'`
if [ ${#mac} -ne 12 ]
then
    echo "Invalid MAC address"
    exit 1
fi

outfile=/tftpboot/$mac.boot

phonetype=$2
fwver=$3

shift; shift; shift

echo "Generating $outfile..."

echo "#!version:1.0.0.1" > $outfile
echo "" >> $outfile
echo "##File header "#!version:1.0.0.1" can not be edited or deleted, and must be placed in the first line.##" >> $outfile
echo "" >> $outfile
echo "[$phonetype]include:config <yealink/$phonetype-$fwver.cfg>" >> $outfile
echo "include:config <yealink/common.cfg>" >> $outfile
echo "include:config <yealink/account-common.cfg>" >> $outfile

line=1
while [ $# -ge 1 ]
do
    linefile=$1-$line.cfg
    if [ ! -f /tftpboot/yealink/$linefile ]
    then
        echo "   Line $line - extension $1 invalid"
    else
        echo "   Line $line - $1"
        echo "include:config <yealink/$linefile>" >> $outfile 
    fi
    shift
    line=$((line+1))
done

echo "" >> $outfile     
echo "overwrite_mode = 1" >> $outfile
echo "specific_model.excluded_mode=0" >> $outfile

chmod 644 $outfile
chown asterisk:asterisk $outfile

