#!/bin/sh

TMPFILE=/tmp/mkpb$$

grep callerid /etc/asterisk/pjsip.endpoint.conf > $TMPFILE

while read -r line
do

    x=`echo $line | cut -f2- -d'='`
    extn=`echo $x | cut -f2 -d'<' | cut -f1 -d'>'`

    /usr/local/bin/rebootphone $extn

done < $TMPFILE

rm -f $TMPFILE
