#!/bin/sh

mklinefile() {

    outfile="/tftpboot/yealink/$2-$1.cfg"
    echo $outfile

    echo "#!version:1.0.0.1" > $outfile
    echo "" >> $outfile
    echo "linekey.$1.type = 15" >> $outfile
    echo "" >> $outfile
    echo "account.$1.enable = 1" >> $outfile
    echo "account.$1.auth_name = $2" >> $outfile
    echo "account.$1.user_name = $2" >> $outfile

    chmod 644 $outfile
    chown asterisk:asterisk $outfile
}

for n in {0..99}
do
    if [ $n -lt 10 ]
    then
        extn="260$n"
    else
        extn="26$n"
    fi

    for x in {1..2}
    do
        mklinefile $x $extn
    done

done
